Remove lfs
springboard-curriculum/mec-mini-projects pull request #5
Opened 2021-03-02 18:42 UTC by arnaudsj

Hi Jhenna,

All the datasets except 1 should not be using LFS anymore, zipped them all, and updated the notebooks (hopefully did not miss any).

Please create a Google Drive Shared folder owned by Springboard when you have a second, share it with me so that I can add the only file that can't be compressed < 100 Mo (combined_data.csv in the recommendation mini project). and I can then update the pointer in the notebook and remove it from the repo as well.

Do not merge as is though, I want to make sure we get all the files in one sweep merge against the main branch.

Thanks!

2021-03-02 23:24 UTC, arnaudsj commented
@jvoorhis-sb just added the Google drive download. Please review and merge if everything looks good!

2021-03-03 00:31 UTC, jvoorhis-sb commented on mec-17.4.1-recommendation-systems-mini-project/Mini_Project_Recommendation_Systems.ipynb
> +    "# Dowload large file from Sprinboard's shared GDrive folder\n",
Could you take out the word Springboard here and just say "the shared GDrive"? That way it is transferable for UP versions.

2021-03-03 00:32 UTC, jvoorhis-sb requested changes
One tiny change in the notebook for 17.4.1

2021-03-03 01:21 UTC, jvoorhis-sb approved these changes
Looks good!

2021-03-03 01:21 UTC, merged